#!/usr/bin/env python3

import sys
from src.lexer import Lexer
from src.parser import Parser
from src.interpreter import Interpreter
from src.abstract_syntax_tree import AbstractSyntaxTree

class Orchestrator:
    # def __init__(self):
    #     self.lexer = Lexer()
    #     self.parser = Parser()
    #     self.interpreter = Interpreter()

    def execute(self, code):
        lexer = Lexer(code)
        lexer.process_source_code()
        tokens = lexer.get_tokens()

        parser = Parser(tokens)
        statements = parser.parse()

        # if statements:
        interpreter = Interpreter()
        interpreter.interpret(statements)

        if False:
            print("SOURCE CODE : ", code)
            print("TOKENS      : ", tokens)
            print("STATEMENTS  : ", *[str(AbstractSyntaxTree(st)) for st in statements])
            print("ENVIRONMENT : ", *interpreter.environment.bindings)

    def interpret_file(self, filename):
        pass

    def run_repl(self):
        while True:
            try:
                sys.stdout.write('$ ')
                line = input()
                if line is None:
                    break
                self.execute(line)
            except (EOFError, KeyboardInterrupt):
                break

        print()


if __name__ == '__main__':
    if len(sys.argv) > 2:
        sys.stderr.write('Usage: ' + sys.argv[0] + ' [filename]\n')
        sys.exit(1)

    orchestrator = Orchestrator()

    if len(sys.argv) == 2:
        orchestrator.interpret_file(sys.argv[1])
    else:
        orchestrator.run_repl()

    sys.exit(0)
