LEFT_PAREN '('; RIGHT_PAREN ')'; LEFT_SQUARE '['; RIGHT_SQUARE ']'; LEFT_CURLY '{'; RIGHT_CURLY '}'; EOL
LEFT_PAREN '('; RIGHT_PAREN ')'; LEFT_SQUARE '['; RIGHT_SQUARE ']'; LEFT_CURLY '{'; RIGHT_CURLY '}'; EOL
EOF